# coding=utf-8

API_KEY = "041020917953e29f2ce60c7efbff8267"
API_SECRET = "516a533d729f4c498fbdfe121fb9f352"

USER = "LeoFtw"
DIRECTORY = "/home/leod/share/music/"
SUB_DIRECTORY = "tagged"

MIN_WEIGHT = 30

TAG_WHITELIST = [
	"acoustic",
	"alt-country",
	"alternative",
	"alternative rock",
	"alternative metal",
	"ambient",
	"ambient black metal",
	"atmospheric",
	"atmospheric black metal",
	"avant-garde",
	"avant-garde metal",
	"baroque",
	"black metal",
	"blackened death metal"
	"blues",
	"blues rock",
	"breakcore",
	"brutal death metal",
	"canterbury",
	"chillout",
	"classic rock",
	"classical",
	"contemporary classical",
	"country",
	"country rock",
	"dance",
	"dark ambient",
	"dark folk",
	"dark metal",
	"death metal",
	"deathcore",
	"depressive black metal",
	"depressive rock",
	"doom metal",
	"downtempo",
	"dream pop",
	"drone",
	"drum and bass",
	"dub",
	"dubstep",
	"electronic",
	"emo",
	"experimental",
	"folk",
	"folk metal",
	"folk punk",
	"folk rock",
	"free jazz",
	"funeral doom metal",
	"funk",
	"garage rock",
	"glam rock",
	"goa",
	"gothic",
	"gothic metal",
	"gothic rock",
	"grindcore",
	"groove metal",
	"grunge",
	"hamburger schule",
	"hard rock",
	"hardcore",
	"hardcore punk",
	"heavy metal",
	"hip-hop",
	"house",
	"idm",
	"indie",
	"indie folk",
	"indie pop",
	"indie rock",
	"industrial",
	"industrial metal",
	"industrial rock",
	"instrumental",
	"instrumental hip-hop",
	"jazz",
	"jazz fusion",
	"jazz metal",
	"jazz rock",
	"krautrock",
	"lo-fi",
	"math metal",
	"math rock",
	"mathcore",
	"melodic black metal",
	"melodic death metal",
	"melodic hardcore",
	"metal",
	"metalcore",
	"minimal",
	"minimalism",
	"ndw",
	"neofolk",
	"new wave",
	"noise",
	"noise rock",
	"nu metal",
	"nwobhm",
	"pop",
	"pop punk",
	"pop rock",
	"post-black metal",
	"post-hardcore",
	"post-metal",
	"post-punk",
	"post-rock",
	"power metal",
	"power pop",
	"progressive",
	"progressive black metal",
	"progressive death metal",
	"progressive metal",
	"progressive rock",
	"proto-punk",
	"psytrance",
	"psychedelic",
	"psychedelic rock",
	"punk",
	"punk rock",
	"reggae",
	"rock",
	"shoegaze",
	"singer-songwriter",
	"slowcore",
	"sludge",
	"soul",
	"soundtrack",
	"stoner metal",
	"stoner rock",
	"symphonic metal",
	"technical death metal",
	"techno",
	"trip-hop",
]
TRANSLATE_TAGS = {
    "hip hop": u"hip-hop",
    "synth-pop": u"synthpop",
    "electronica": u"electronic",
	"avantgarde black metal": u"avant-garde metal",
	"avantgarde": u"avant-garde",
	"drum n bass": u"drum and bass",
	"freakfolk": u"freak folk",
	"nu-metal": u"nu metal",
	"alt country": u"alt-country",
}
TAG_MIN_WEIGHT = 30

ARTIST_NAME_FIXES = {
	u"godspeed you black emperor!": "godspeed you! black emperor",
	u"negura bunget": u"negură bunget",
	u"dave brubeck quartet the": "the dave brubeck quartet",
	u"dave brubeck": "the dave brubeck quartet",
	u"gza": "gza/genius",
    u"soap & skin": "soap&skin",
    u"alan parsons": "the alan parsons project",
    u"getz, stan": "stan getz",
    u"the arcade fire": "arcade fire",
	u"motorhead": "motörhead",
	u"jimi hendrix": "the jimi hendrix experience",
	u"boehse onkelz": "böhse onkelz",
}

ALBUM_NAME_FIXES = {
	u"65daysofstatic": { u"the destruction of small ideals": u"the destruction of small ideas" },
	u"baroness": { u"red": u"red album", u"blue" : u"blue record" },
	u"wu-tang clan": { u"enter the wu-tang (36 chambers)": u"enter the wu-tang: 36 chambers" },
	u"sleep": { u"holy mountain": u"sleep's holy mountain" },
	u"justice": { u"cross": u"✝" },
}
